# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(default=0)),
                ('productimg', models.CharField(max_length=256)),
                ('productname', models.CharField(max_length=128)),
                ('productlongname', models.CharField(max_length=256)),
                ('isxf', models.BooleanField(default=0)),
                ('pmdesc', models.BooleanField(default=0)),
                ('specifics', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0)),
                ('marketprice', models.FloatField(default=1)),
                ('categoryid', models.IntegerField(default=0)),
                ('childcid', models.IntegerField(default=0)),
                ('childcidname', models.CharField(max_length=256)),
                ('dealerid', models.IntegerField(default=0)),
                ('storenums', models.IntegerField(default=0)),
                ('productnum', models.IntegerField(default=0)),
                ('o_goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.OrderGoods')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_ordered_time', models.DateTimeField(auto_created=True)),
                ('o_status', models.IntegerField(default=0)),
                ('o_price', models.FloatField(default=0)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userModel')),
            ],
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='o_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderModel'),
        ),
    ]
