# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-19 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='o_ordered_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 6, 19, 17, 22, 12, 770040)),
        ),
    ]
